[package]
name = "grees"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.3.5"
serde_json = "1.0.97"
pnet = "0.33.0"
magic-crypt = "3.1.12"
aes = "0.8.3"
base64 = "0.21.2"
typenum = "1.16.0"
block-padding = "0.3.3"
